### ISSUE TITLE
Dependency build, but missing in python?

### ISSUE THREAD

**Issue by TyberiusPrime** [adisbladis/uv2nix#12]
I'm not sure what's going on, it's building ftw-table, but then it's not present when building the app from the workspace.

```
       > Checking runtime dependencies for app-0.1.0-py3-none-any.whl
       >   - ftw-table not installed
```

Reproduction example in 
https://github.com/TyberiusPrime/20240913_uv2nix_ftw-table

**Comment by adisbladis** [comment]
This is actually nixpkgs brokenness: The runtime dependency hooks doesn't do normalization.
You can change your dependency declaration to look like use the dotted name instead of the dashed one:
`"ftw-table==1.22.0"` -> `"ftw.table==1.22.0"`

**Comment by TyberiusPrime** [comment]
Eh, I'm working from a list that's already normalized.
I guess I can query pypi for the correct name.

But I think it's likely that there's going to be at least one package that requires something with a normalized name instead of the 'true name'.

Unfortunately, reading the hook, it's probably a problem not even in nixpkgs, but in importlib.metadata.distribution not taking a normalized name.

**Comment by TyberiusPrime** [comment]
> But I think it's likely that there's going to be at least one package that requires something with a normalized name instead of the 'true name'.

And there it is, pdfquery-0.4.3 requesting "pdfminer.six", which apparently get's normalized somewhere and then pdfquery fail's it's runtime dependency check.

**Comment by TyberiusPrime** [comment]
There's also something funky around this with prereleases.
trying to build gcs_oauth2_boto_plugin 3.2, I get
'retry-decorator>=1.0.0 not satisfied by version 2.0a1'

**Comment by adisbladis** [comment]
This should be reported and tracked in nixpkgs. I don't consider this a uv2nix bug.

**Comment by TyberiusPrime** [comment]
> This should be reported and tracked in nixpkgs. I don't consider this a uv2nix bug.

I agree. 

I'd also suggest we add the workaround 'you must use the true name of python packages in your requirements' to our (eventual) faq.
