### ISSUE TITLE
Handling infinite recursion

### ISSUE THREAD

**Issue by TyberiusPrime** [adisbladis/uv2nix#13]
When python packages depend on each other in a cycle,
we need to break the infinite recursion.

I had though this would work like poetry2nix, 
```
        dark-matter = prev.dark-matter.overridePythonAttrs (
          old: {
            propagatedBuildInputs =
              removePackagesByName
              (builtins.trace (old.propagatedBuildInputs or []) (old.propagatedBuildInputs or []))
              (pkgs.lib.optionals (final ? gb2seq) [final.gb2seq]);
          }
        );
```

But at that point in the eval, propagatedBuildInputs is still empty, and therefore the recursion remains.

Reproduction repo in https://github.com/TyberiusPrime/20240914_uv2nix_infinite_recursion

Perhaps you can shine some light on how to do this, @adisbladis ? 
Thanks!

**Comment by adisbladis** [comment]
The new pyproject.nix builders support cyclic dependencies and were added in https://github.com/adisbladis/uv2nix/pull/17.
Cyclic dependencies aren't supported using nixpkgs builders, which will likely be removed shortly.
