### ISSUE TITLE
support for PEP 735 (`dependency-groups`)

### ISSUE THREAD

**Issue by cpcloud** [adisbladis/uv2nix#43]
Similar to [`poetry`'s dependency groups](https://python-poetry.org/docs/managing-dependencies/#dependency-groups), there's now [an official way](https://peps.python.org/pep-0735/) to specify these in a canonical `pyproject.toml` and it's [supported in `uv`](https://docs.astral.sh/uv/concepts/dependencies/#dependency-groups).

**Comment by adisbladis** [comment]
I started adding PEP-735 support to pyproject.nix the other day: https://github.com/nix-community/pyproject.nix/tree/pep735.
It's not done yet (still needs an interface in the project abstraction).
